### ISSUE TITLE
Code Refactor of Handing the LOB API Key

### ISSUE THREAD

**Issue by Alex-is-Gonzalez** [OpenSourceFellows/amplify#976]
# Task
You will be working in this file : https://github.com/OpenSourceFellows/amplify/blob/main/server/routes/api/lob.js

```Javascript
// Temporary implementation for fallback with deprecation warnings line 396 - 417
function getLobApiKey() {
  const { LOB_API_KEY, LiveLob } = process.env
  const lobApiKey = LOB_API_KEY || LiveLob

  if (LiveLob) {
    if (LOB_API_KEY) {
      console.warn('Using "LOB_API_KEY" environment variable.')
      console.warn(
        'Please remove your deprecated "LiveLob" environment variable!'
      )
    } else {
      console.warn('Expected "LOB_API_KEY" environment variable was not found.')
      console.warn(
        'Falling back to deprecated "LiveLob" environment variable....'
      )
      console.warn('Please update your environment to use the expected key!')
    }
  }

  return lobApiKey
}
```
To update this code for better security, clarity, and handling of deprecated environment variables, you can refactor it as follows:
Ask AI to refactor this code snippet  to handle error, warning and constant. You should be able to copy the code about and the tasks and ask for an output

- [x] Error Handling: Instead of just logging warnings, you can throw errors if the expected environment variable is missing.
- [x] Clarify Warnings: Ensure the warnings are clear and actionable.
- [x] Use Constants: Define constants for environment variables to make the code more readable.

**Comment by Dunridge** [comment]
Branch: [issue-976](https://github.com/ProgramEquity/amplify/tree/issue-976)

**Comment by Dunridge** [comment]
Branch: [issue-976](https://github.com/ProgramEquity/amplify/tree/issue-976)
